### ISSUE TITLE
failed to call API after deploymnet using docker-compose

### ISSUE THREAD

**Issue by maxwellhertz** [micro/go-micro#1141]
I used docker-compose to deploy `go.micro.srv.greeter` and `go.micro.api.greeter` from [greeter](https://github.com/micro/examples/tree/master/greeter). I also deployed micro as an API gateway. The `docker-compose.yml` file is as follows:

```yml
version: "3.7"

services:
    micro:
        image: micro/micro:latest
        command: api
        ports: 
            - "8080:8080"
        networks: 
            - microapp

    greeter-server:
        image: micro-greeter-server # of course I built this image and micro-greeter-api myself
        environment: 
            - MICRO_SERVER_ADDRESS=:50051
        ports: 
            - 50051
        networks: 
            - microapp
    
    greeter-api:
        image: micro-greeter-api
        environment: 
            - MICRO_SERVER_ADDRESS=:50052
        ports: 
            - 50052
        networks: 
            - microapp
   
networks: 
    microapp:
```

All services started and registered successfully.  

```bash
$ sudo docker exec -it micro ./micro list services

go.micro.api
go.micro.api.gin-greeter
go.micro.api.greeter
go.micro.http.broker
go.micro.srv.greeter
```

I got an error when I tried to call the API:

```bash
$ curl http://localhost:8080/greeter/say/hello?name=john

{"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
```
Could anyone help? Tks.
