### ISSUE TITLE
How to use store?

### ISSUE THREAD

**Issue by alexeyco** [micro/go-micro#1567]
Hi there!

main.go of my service:
```go
package main

import (
	//...
)

const serviceName = "my.srv.awesome";

func main() {
	//...
	srv := micro.NewService(
		micro.Name(serviceName),
		micro.Version("latest"),
		micro.BeforeStart(func() (err error) {
			s := service.NewStore()
			key := fmt.Sprintf("%s.node", serviceName)

			var r []*store.Record
			if r, err = s.Read(key, store.ReadLimit(1)); err != nil {
				return
			}

			var node int64 = 0
			if len(r) == 1 {
				node = int64(binary.BigEndian.Uint64(r[0].Value))
			}

			node++
			rec := &store.Record{Key: key}
			binary.BigEndian.PutUint64(rec.Value, uint64(node))

			log.Debug("My awesome node: %d", node)

			return
		}),
	)
	//...
}
```

And docker-compose.yml
```yml
version: '3.7'

services:
  web:
    command: web
    image: microhq/micro:latest
    ports:
      - 8082:8082
    networks:
      - internal

  store:
    command: store
    image: microhq/micro:latest
    networks:
      - internal

  srv:
    image: micromaniacs/golang:1.14.1
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/alexeyco/my-awesome-srv
    working_dir: /go/src/github.com/alexeyco/my-awesome-srv
    command: tail -f /dev/null
    networks:
      - internal

networks:
  internal:
    external: false
```

Ok, let's start service:
```
$ go run main.go
2020-04-24 03:09:27  level=info Starting [service] my.srv.awesome
2020-04-24 03:09:27  level=fatal {"id":"go.micro.store","code":500,"detail":"not found","status":"Internal Server Error"}
```

But:
```
$ micro list services
go.micro.store
go.micro.web
```

Micro version micro version v2.5.0-6484a86-1587040401.

What am I doing wrong?
