### ISSUE TITLE
[BUG] go micro application always getting “/greeter-srv” no such file or directory kubernetes

### ISSUE THREAD

**Issue by SHUFIL** [micro/go-micro#1864]
**Describe the bug**

1. What are you trying to do?
 installing micro in kubernetes
2. What did you expect to happen?
why its getting error , tell me exactly how to install this micro service 
getting error starting container process caused "exec: \"/greeter-srv\": stat /greeter-srv: no such file or directory": unknown

3. What happens instead?
need to install micro in kuberenetes
**How to reproduce the bug:**
 install micro in kubernetes 
If possible, please include a minimal code snippet here.
Dockerfile
```
 FROM alpine:latest
RUN apk --no-cache add make git go gcc libtool musl-dev
WORKDIR /go/src/
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin
COPY . .
COPY greeter-srv /go/src/
RUN make

RUN apk add ca-certificates && \
    rm -rf /var/cache/apk/* /tmp/* && \
    [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf

ENTRYPOINT ["/greeter-srv"]
```
yaml file

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-srv
  template:
    metadata:
      labels:
        app: greeter-srv
    spec:
      containers:
        - name: greeter
          command: [
        "/greeter-srv",
      ]
          image: 12345.dkr.ecr.ap-south-1.amazonaws.com/micro:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: greeter-port
          env:
          - name: MICRO_SERVER_ADDRESS
            value: "0.0.0.0:8080"
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats-cluster"
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
      imagePullSecrets:
      - name: ap-south-1-ecr-registry
```

greeter-srv file
.

```
import (
    "github.com/micro/go-micro/v2"
)
func main() {
    service := micro.NewService(
        micro.Name("greeter")
    )
    service.Init()
    service.Run()
}
```

Error log: please paste `log` output here
   Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  <unknown>           default-scheduler  Successfully assigned default/greeter-7d7c644bdc-dk5q2 to minikube
  Normal   Pulling    9s (x4 over 3m10s)  kubelet, minikube  Pulling image "12345.dkr.ecr.ap-south-1.amazonaws.com/micro:latest"
  Normal   Pulled     9s (x4 over 61s)    kubelet, minikube  Successfully pulled image "460378929709.dkr.ecr.ap-south-1.amazonaws.com/micro:latest"
  Normal   Created    8s (x4 over 59s)    kubelet, minikube  Created container greeter
  Warning  Failed     8s (x4 over 56s)    kubelet, minikube  Error: failed to start container "greeter": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/greeter-srv\": stat /greeter-srv: no such file or directory": unknown
```
please paste `go env` output here
```
