### ISSUE TITLE
Service Discovery using docker-compose

### ISSUE THREAD

**Issue by aryan9600** [micro/go-micro#1890]
I am using go-micro for service discovery between a gRPC server and client. I am trying to run them using docker-compose but it seems like the client fails to find the server. 

`docker-compose.yml`
```
version: '3.5'

services:
    consignment:
        restart: always
        build: ./service-consignment
        ports:
            - 0.0.0.0:50051:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"
    cli:
         build: ./cli-consignment
         depends_on:
             - consignment
```

Error: `cli_1 | 2020-08-01 12:50:49.218277 I | Could not greet: {"id":"go.micro.client","code":500,"detail":"service service.consignment: not found","status":"Internal Server Error"}
delivery-system_cli_1 exited with code 1`

Where might I be going wrong?
