### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by adxgun** [micro/go-micro#507]
Hello,
Thanks for the great work being done here, it is incredible!

So, i have been trying to setup my project in such a way that'll allow inter-service comm with `rpc` and will expose http REST api to clients.

For the http REST api, i am using **Gin** framework.

Whenever i try to access my service on `localhost:8080/account/hello`, i am always getting either `404 not found` from GIN or `500 internal server error` from micro. Below is my `docker-compose.yml`

```yaml 
version: "3"

services:
  micro:
    command: --registry_address=consul:8500 api --handler=http
    image: microhq/micro:latest
    links:
      - consul
      - hello
    ports:
      - "8080:8080"
  hello:
    build: .
    restart: on-failure
    command: --registry_address=consul:8500
    links:
      - consul
  consul:
    command: -server -bootstrap -rejoin
    image: progrium/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
```

And my example code
```Go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/micro/go-web"
	"log"
)

type App struct {}

func (a *App) Hello(c *gin.Context) {
	log.Println("Serving ", c.Request.RequestURI)
	c.JSON(200, gin.H{"hello" : "World!"})
}

func main() {
	service := web.NewService(web.Name("go.micro.api.account"))
	if err := service.Init(); err != nil {
		log.Fatal("failed to init service ", err)
	}

	a := &App{}
	router := gin.Default()
	router.NoRoute(func(context *gin.Context) {
		log.Println("not found => ", context.Request.RequestURI)
	})

	router.NoMethod(func(context *gin.Context) {
		log.Printf("method not allow for path %s, method %s", context.Request.RequestURI, context.Request.Method)
	})

	router.GET("/hello", a.Hello)

	service.Handle("/", router)
	if err := service.Run(); err != nil {
		log.Fatal("failed to run service ", err)
	}
}
```
I am little bit confused because when i tried to request for a non-registered GIN route, `router.NoRoute` handler of GIN got called, and when i called a correct/registered GIN route, i got 500 internal server error.

My log output
`consul_1  | ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
consul_1  | ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
consul_1  | ==> Starting raft data migration...
hello_1   | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
hello_1   | 
hello_1   | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
hello_1   |  - using env:       export GIN_MODE=release
hello_1   |  - using code:      gin.SetMode(gin.ReleaseMode)
hello_1   | 
hello_1   | [GIN-debug] GET    /hello                    --> main.(*App).Hello-fm (3 handlers)
hello_1   | 2019/06/09 15:36:21 Listening on [::]:39269
consul_1  | ==> Starting Consul agent...
micro_1   | 2019/06/09 15:36:21 Registering RPC Handler at /rpc
micro_1   | 2019/06/09 15:36:21 Registering API Request Handler at /
micro_1   | 2019/06/09 15:36:21 HTTP API Listening on [::]:8080
micro_1   | 2019/06/09 15:36:21 Transport [http] Listening on [::]:36217
micro_1   | 2019/06/09 15:36:21 Broker [http] Connected to [::]:37481
micro_1   | 2019/06/09 15:36:21 Registry [mdns] Registering node: go.micro.api-a6e0a544-499b-4d65-a87a-92d2796fb657
consul_1  | ==> Starting Consul agent RPC...
consul_1  | ==> Consul agent running!
consul_1  |          Node name: '4e4a7b37bbe0'
consul_1  |         Datacenter: 'dc1'
consul_1  |             Server: true (bootstrap: true)
consul_1  |        Client Addr: 0.0.0.0 (HTTP: 8500, HTTPS: -1, DNS: 53, RPC: 8400)
consul_1  |       Cluster Addr: 192.168.48.2 (LAN: 8301, WAN: 8302)
consul_1  |     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
consul_1  |              Atlas: <disabled>
consul_1  | 
consul_1  | ==> Log data will now stream in as it occurs:
consul_1  | 
consul_1  |     2019/06/09 15:36:20 [INFO] serf: EventMemberJoin: 4e4a7b37bbe0 192.168.48.2
consul_1  |     2019/06/09 15:36:20 [INFO] serf: EventMemberJoin: 4e4a7b37bbe0.dc1 192.168.48.2
consul_1  |     2019/06/09 15:36:20 [INFO] raft: Node at 192.168.48.2:8300 [Follower] entering Follower state
consul_1  |     2019/06/09 15:36:20 [INFO] consul: adding server 4e4a7b37bbe0 (Addr: 192.168.48.2:8300) (DC: dc1)
consul_1  |     2019/06/09 15:36:20 [INFO] consul: adding server 4e4a7b37bbe0.dc1 (Addr: 192.168.48.2:8300) (DC: dc1)
consul_1  |     2019/06/09 15:36:20 [ERR] agent: failed to sync remote state: No cluster leader
consul_1  |     2019/06/09 15:36:22 [WARN] raft: Heartbeat timeout reached, starting election
consul_1  |     2019/06/09 15:36:22 [INFO] raft: Node at 192.168.48.2:8300 [Candidate] entering Candidate state
consul_1  |     2019/06/09 15:36:22 [INFO] raft: Election won. Tally: 1`

Thank You
