### ISSUE TITLE
consul error,plz help~~

### ISSUE THREAD

**Issue by anakin** [micro/go-micro#575]
main.go

```
func main() {
	reg := consul.NewRegistry()
	cmd.Init(
		micro.Name("anakin.sun.api.gateway"),
		micro.Registry(reg),
	)
}
```
Dockerfile:
```
FROM golang
WORKDIR .
COPY ./micro .
EXPOSE 8080 8080
```

docker build . -t anakin/micro:latest

docker-compose.yaml:

```
version: "3"

services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  api-gateway:
    image: anakin/micro
    command: ./micro --registry_address=consul:8500 api --namespace=anakin.sun.api --handler=http
    links:
      - consul
    depends_on:
      - consul
    ports:
      - "8080:8080"

```

so,docker-compose up
then,the output is :
```
2019/07/10 09:04:14 Server go.micro.api-f0dce5a4-8a98-491a-b1f3-8f66be7ff174 register error: Put http://127.0.0.1:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused
2019/07/10 09:04:15 Error listing endpoints Get http://127.0.0.1:8500/v1/catalog/services?stale=: dial tcp 127.0.0.1:8500: connect: connection refused
2019/07/10 09:04:17 Error listing endpoints Get http://127.0.0.1:8500/v1/catalog/services?stale=: dial tcp 127.0.0.1:8500: connect: connection refused

```

so thank you for your help~~~~

**Comment by asim** [comment]
You should not modify the micro api like this. Please specify --registry=consul to the micro api and it will work fine.

**Comment by anakin** [comment]
thank you for your reply!!!
But,I changed my compose file:
```
version: "3"

services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  api-gateway:
    build: ./apigw
    entrypoint: ./micro --registry=consul --registry_address=consul:8500 api --namespace=chope.co.api --handler=http
    links:
      - consul
    ports:
      - "8080:8080"

```

then , docker-compose up
the output is still:
```
consul_1       | ==> Starting raft data migration...
api-gateway_1  | 2019/07/10 11:06:44 Registering RPC Handler at /rpc
api-gateway_1  | 2019/07/10 11:06:44 Registering API HTTP Handler at /{service:[a-zA-Z0-9]+}
api-gateway_1  | 2019/07/10 11:06:44 HTTP API Listening on [::]:8080
consul_1       | ==> Starting Consul agent...
api-gateway_1  | 2019/07/10 11:06:44 Transport [http] Listening on [::]:46203
api-gateway_1  | 2019/07/10 11:06:44 Broker [http] Connected to [::]:46219
api-gateway_1  | 2019/07/10 11:06:44 Registry [consul] Registering node: go.micro.api-0d2d8ec3-8dac-4522-9cbb-bada1f7cb22f
api-gateway_1  | 2019/07/10 11:06:44 Error listing endpoints Get http://127.0.0.1:8500/v1/catalog/services?stale=: dial tcp 127.0.0.1:8500: connect: connection refused
api-gateway_1  | 2019/07/10 11:06:44 [ERR] consul.watch: Watch (type: services) errored: Get http://127.0.0.1:8500/v1/catalog/services: dial tcp 127.0.0.1:8500: connect: connection refused, retry in 5s
consul_1       | ==> Starting Consul agent RPC...
api-gateway_1  | 2019/07/10 11:06:44 Server go.micro.api-0d2d8ec3-8dac-4522-9cbb-bada1f7cb22f register error: Put http://127.0.0.1:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused
```


why the address is 127.0.0.1:8500?

**Comment by anakin** [comment]
and ,in the api container

in file: /etc/hosts
there is no consul info....
```
root@018bb9132c75:/go# more /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.26.0.3	018bb9132c75

```

**Comment by milosgajdos** [comment]
This ssuggests some `docker-compose` issue rather than `go-micro` @anakin 

I'm wondering, if you set `hostname: consul` in your `consul` stanza, would that help?

Either way, `docker-compose` not populating `/etc/hosts` properly is strange, because `v3`+ should be doing what you are expecting it do based on the [official docs](https://docs.docker.com/compose/compose-file/).

I'm also wondering if upgrading `docker-compose` would help, depending on the version you are using.

**Comment by anakin** [comment]
> This ssuggests some `docker-compose` issue rather than `go-micro` @anakin
> 
> I'm wondering, if you set `hostname: consul` in your `consul` stanza, would that help?
> 
> Either way, `docker-compose` not populating `/etc/hosts` properly is strange, because `v3`+ should be doing what you are expecting it do based on the [official docs](https://docs.docker.com/compose/compose-file/).
> 
> I'm also wondering if upgrading `docker-compose` would help, depending on the version you are using.

Thank you so much!!!!!!
I finally fixed this by using  microhq/micro image ,here is my docker-compose.yaml:
```
version: "3"

services:
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  micro:
    command: --registry=consul --registry_address=consul:8500 api --handler=http --namespace=anakin.sun.api
    image: microhq/micro:latest
    links:
      - consul
      - api
    ports:
      - "8080:8080"
  api:
    build: ./build/api
    entrypoint: ./api --registry=consul --registry_address=consul:8500
    links:
      - consul
      - nats
      - user-service
  user-service:
    build: ./build/user-service
    entrypoint: ./user-service --registry=consul --registry_address=consul:8500 --broker=nats --broker_address=nats
    links:
      - consul
      - nats
```
It works!!

Thank you again!!
