### ISSUE TITLE
deploy @k8s,health sidecar error

### ISSUE THREAD

**Issue by anakin** [micro/go-micro#633]
I used the default yaml file:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeter-srv
    spec:
      containers:
        - name: greeter
          command: [
            "/greeter-srv",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
          ]
          image: microhq/greeter-srv:kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: greeter-port
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=greeter",
            "--server_address=0.0.0.0:8080"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
```

after deployed ,there is en error below:
`Liveness probe failed: HTTP probe failed with statuscode: 500
`
